### ISSUE TITLE
你好，可以请教一下 CaptchaGenerator.php  这么用吗

### ISSUE THREAD

**Issue by 583** [chxj1992/captcha_cracker#1]
我composer安装完以后cli运行php .\CaptchaGenerator.php老是提示

PHP Fatal error:  Uncaught RuntimeException: A facade root has not been set.

**Comment by chxj1992** [comment]
这个其实不能直接运行,  因为只是一个代码片段,  放进来的意义主要是可以看看.  抱歉文档里说的不是很清楚, 具体生成验证码图片的方法,  可以结合 captcha 原项目看看, 希望能帮到你
